name: Build the package and publish it to pypi

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: whynothugo/python-linting@master
